///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JoinClubResponseDataClubsPelatih {
/*
{
  "id": "38c63457-3e46-42d8-aa8f-f00c86a9b584",
  "name": "PelatihA",
  "alamat": "Jl. Aspal Gg. Barokah",
  "no_hp": "081258988237",
  "jenis_kelamin": "LAKI-LAKI",
  "tgl_lahir": "1999-05-19",
  "url_foto": null,
  "email": "pelatiha@email.com",
  "email_verified_at": null,
  "created_at": "2021-05-28T13:37:00.000000Z",
  "updated_at": "2021-05-28T13:37:00.000000Z"
} 
*/

  String? id;
  String? name;
  String? alamat;
  String? noHp;
  String? jenisKelamin;
  String? tglLahir;
  String? urlFoto;
  String? email;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;

  JoinClubResponseDataClubsPelatih({
    this.id,
    this.name,
    this.alamat,
    this.noHp,
    this.jenisKelamin,
    this.tglLahir,
    this.urlFoto,
    this.email,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
  });
  JoinClubResponseDataClubsPelatih.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    alamat = json["alamat"]?.toString();
    noHp = json["no_hp"]?.toString();
    jenisKelamin = json["jenis_kelamin"]?.toString();
    tglLahir = json["tgl_lahir"]?.toString();
    urlFoto = json["url_foto"]?.toString();
    email = json["email"]?.toString();
    emailVerifiedAt = json["email_verified_at"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["alamat"] = alamat;
    data["no_hp"] = noHp;
    data["jenis_kelamin"] = jenisKelamin;
    data["tgl_lahir"] = tglLahir;
    data["url_foto"] = urlFoto;
    data["email"] = email;
    data["email_verified_at"] = emailVerifiedAt;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    return data;
  }
}

class JoinClubResponseDataClubs {
/*
{
  "id": "41e6cb43-0737-4da7-915c-a7bc76673afc",
  "nama_klub": "Klub A",
  "deskripsi": "Ini adalah klub A",
  "coordinat": "-0.018567935928678118, 109.33916098754045",
  "alamat": "Tengah Sungai Kapuas",
  "url_foto": null,
  "pelatih": {
    "id": "38c63457-3e46-42d8-aa8f-f00c86a9b584",
    "name": "PelatihA",
    "alamat": "Jl. Aspal Gg. Barokah",
    "no_hp": "081258988237",
    "jenis_kelamin": "LAKI-LAKI",
    "tgl_lahir": "1999-05-19",
    "url_foto": null,
    "email": "pelatiha@email.com",
    "email_verified_at": null,
    "created_at": "2021-05-28T13:37:00.000000Z",
    "updated_at": "2021-05-28T13:37:00.000000Z"
  }
} 
*/

  String? id;
  String? namaKlub;
  String? deskripsi;
  String? coordinat;
  String? alamat;
  String? urlFoto;
  JoinClubResponseDataClubsPelatih? pelatih;

  JoinClubResponseDataClubs({
    this.id,
    this.namaKlub,
    this.deskripsi,
    this.coordinat,
    this.alamat,
    this.urlFoto,
    this.pelatih,
  });
  JoinClubResponseDataClubs.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    namaKlub = json["nama_klub"]?.toString();
    deskripsi = json["deskripsi"]?.toString();
    coordinat = json["coordinat"]?.toString();
    alamat = json["alamat"]?.toString();
    urlFoto = json["url_foto"]?.toString();
    pelatih = (json["pelatih"] != null)
        ? JoinClubResponseDataClubsPelatih.fromJson(json["pelatih"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["nama_klub"] = namaKlub;
    data["deskripsi"] = deskripsi;
    data["coordinat"] = coordinat;
    data["alamat"] = alamat;
    data["url_foto"] = urlFoto;
    if (pelatih != null) {
      data["pelatih"] = pelatih!.toJson();
    }
    return data;
  }
}

class JoinClubResponseData {
/*
{
  "clubs": [
    {
      "id": "41e6cb43-0737-4da7-915c-a7bc76673afc",
      "nama_klub": "Klub A",
      "deskripsi": "Ini adalah klub A",
      "coordinat": "-0.018567935928678118, 109.33916098754045",
      "alamat": "Tengah Sungai Kapuas",
      "url_foto": null,
      "pelatih": {
        "id": "38c63457-3e46-42d8-aa8f-f00c86a9b584",
        "name": "PelatihA",
        "alamat": "Jl. Aspal Gg. Barokah",
        "no_hp": "081258988237",
        "jenis_kelamin": "LAKI-LAKI",
        "tgl_lahir": "1999-05-19",
        "url_foto": null,
        "email": "pelatiha@email.com",
        "email_verified_at": null,
        "created_at": "2021-05-28T13:37:00.000000Z",
        "updated_at": "2021-05-28T13:37:00.000000Z"
      }
    }
  ],
  "base_foto": "http://localhost:8000/images/users"
} 
*/

  List<JoinClubResponseDataClubs?>? clubs;
  String? baseFoto;

  JoinClubResponseData({
    this.clubs,
    this.baseFoto,
  });
  JoinClubResponseData.fromJson(Map<String, dynamic> json) {
    if (json["clubs"] != null) {
      final v = json["clubs"];
      final arr0 = <JoinClubResponseDataClubs>[];
      v.forEach((v) {
        arr0.add(JoinClubResponseDataClubs.fromJson(v));
      });
      clubs = arr0;
    }
    baseFoto = json["base_foto"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (clubs != null) {
      final v = clubs;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["clubs"] = arr0;
    }
    data["base_foto"] = baseFoto;
    return data;
  }
}

class JoinClubResponseMeta {
/*
{
  "code": 200,
  "status": true,
  "message": "Berhasil mengambil data"
} 
*/

  int? code;
  bool? status;
  String? message;

  JoinClubResponseMeta({
    this.code,
    this.status,
    this.message,
  });
  JoinClubResponseMeta.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    status = json["status"];
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["status"] = status;
    data["message"] = message;
    return data;
  }
}

class JoinClubResponse {
/*
{
  "meta": {
    "code": 200,
    "status": true,
    "message": "Berhasil mengambil data"
  },
  "data": {
    "clubs": [
      {
        "id": "41e6cb43-0737-4da7-915c-a7bc76673afc",
        "nama_klub": "Klub A",
        "deskripsi": "Ini adalah klub A",
        "coordinat": "-0.018567935928678118, 109.33916098754045",
        "alamat": "Tengah Sungai Kapuas",
        "url_foto": null,
        "pelatih": {
          "id": "38c63457-3e46-42d8-aa8f-f00c86a9b584",
          "name": "PelatihA",
          "alamat": "Jl. Aspal Gg. Barokah",
          "no_hp": "081258988237",
          "jenis_kelamin": "LAKI-LAKI",
          "tgl_lahir": "1999-05-19",
          "url_foto": null,
          "email": "pelatiha@email.com",
          "email_verified_at": null,
          "created_at": "2021-05-28T13:37:00.000000Z",
          "updated_at": "2021-05-28T13:37:00.000000Z"
        }
      }
    ],
    "base_foto": "http://localhost:8000/images/users"
  }
} 
*/

  JoinClubResponseMeta? meta;
  JoinClubResponseData? data;

  JoinClubResponse({
    this.meta,
    this.data,
  });
  JoinClubResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null)
        ? JoinClubResponseMeta.fromJson(json["meta"])
        : null;
    data = (json["data"] != null)
        ? JoinClubResponseData.fromJson(json["data"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
